version: '3.8'

services:
  mongodb_prod:
    image: mongo:latest
    container_name: footapp_mongodb_prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-FootClubApp_Prod}
    volumes:
      - mongodb_data_prod:/data/db
    ports:
      - "27017:27017"

  web_prod:
    build: .
    container_name: footapp_web_prod
    restart: always
    depends_on:
      - mongodb_prod
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-secret}@mongodb_prod:27017/${MONGO_DATABASE:-FootClubApp_Prod}?authSource=admin
      - FLASK_ENV=production
    ports:
      - "5000:5000"

volumes:
  mongodb_data_prod:
