services:
  traefik:
    image: traefik:v2.11
    container_name: footapp_traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - root_default
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik_data/acme.json:/acme.json
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=root_default"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:8443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=anibasoufiane2001@gmail.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/acme.json"

networks:
  root_default:
    external: true
