services:
  mongodb_prod:
    image: mongo:latest
    container_name: footapp_mongodb_prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-FootClubApp_Prod}
    volumes:
      - mongodb_data_prod:/data/db
    ports:
      - "27017:27017"

  web_prod:
    build: .
    container_name: footapp_web_prod
    restart: always
    depends_on:
      - mongodb_prod
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-secret}@mongodb_prod:27017/${MONGO_DATABASE:-FootClubApp_Prod}?authSource=admin
      - FLASK_ENV=production
    networks:
      - default
      - traefik_public
    labels:
      - "traefik.enable=true"
      # Router HTTPS
      - "traefik.http.routers.footapp-prod.rule=Host(`takurte.fr`) || Host(`www.takurte.fr`)"
      - "traefik.http.routers.footapp-prod.entrypoints=websecure"
      - "traefik.http.routers.footapp-prod.tls=true"
      - "traefik.http.routers.footapp-prod.tls.certresolver=myresolver"
      - "traefik.http.routers.footapp-prod.middlewares=prod-redirect"
      # Router HTTP (for redirect)
      - "traefik.http.routers.footapp-prod-http.rule=Host(`takurte.fr`) || Host(`www.takurte.fr`)"
      - "traefik.http.routers.footapp-prod-http.entrypoints=web"
      - "traefik.http.routers.footapp-prod-http.middlewares=prod-redirect"
      # Middleware redirect
      - "traefik.http.middlewares.prod-redirect.redirectscheme.scheme=https"
      # Service
      - "traefik.http.services.footapp-prod.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik_public"

volumes:
  mongodb_data_prod:


networks:
  traefik_public:
    external: true
